[project]
name = "folio-to-blue-core-technical-services-workflow"
version = "0.1.0"
description = "Demostration on using AI agentic harnesses for a technical services workflow using FOLIO and Blue Core"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bluecore-client>=0.1.0",
    "bluecore-models>=0.29.0",
    "folioclient>=1.0.11",
    "jupyterlab>=4.6.3",
    "pyshacl>=0.40.1",
]
